### ISSUE TITLE
FIXED | switchinplayer and switchoutplayer was renamed to switchToMultiSecondpart

### ISSUE THREAD

**Issue by YannickGTHD** [JoshuaGerke/altv-skycam#1]
Hey, as the heading says, Alt:V changed something about the skycam. It's not working anymore. Can you update this resource? 
It kind of works with the new names but I think something is still missing, the cam is not flying. 

https://natives.altv.mp/#/0xAAB3200ED59016BC

**Comment by JoshuaGerke** [comment]
I see, i check the new Natives and fix that SAP!

**Comment by JoshuaGerke** [comment]
Fixed so far.
